sudo: required
dist: trusty
language: scala
scala:
 - 2.11.8
env:
 - export LD_LIBRARY_PATH=/usr/local/lib
script:
 - mvn install -DskipTests
jdk:
 - oraclejdk8
notifications:
 email:
  - ops@acinq.fr
