sudo: required
dist: trusty
language: scala
scala:
 - 2.11.8
before_install:
 - source travis/builddeps.sh
env:
 - export LD_LIBRARY_PATH=/usr/local/lib
script:
 - mvn install && cd eclair-node
jdk:
 - oraclejdk8
notifications:
 email:
  - ops@acinq.fr
